//
//  CameraTranslatorRouter.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 27/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CameraTranslatorRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CameraTranslatorDataPassing
{
  var dataStore: CameraTranslatorDataStore? { get }
}

class CameraTranslatorRouter: NSObject, CameraTranslatorRoutingLogic, CameraTranslatorDataPassing
{
  weak var viewController: CameraTranslatorViewController?
  var dataStore: CameraTranslatorDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CameraTranslatorViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CameraTranslatorDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
