//
//  CameraTranslatorWorker.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 27/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CameraTranslatorWorker
{
    let photoLibrary = PhotosLibrary()
    
    func getLatestImage(for target : UIImageView,completion : @escaping (UIImage) -> ()){
        photoLibrary.fetchLatestPhoto(target: target) { (image) in
            
            completion(image)
            
        }
    }
}
