//
//  ChooseLanguagesWorker.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 22/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChooseLanguagesWorker
{
    func getLanguages<ResponseType: Decodable>(url : URL, responseType : ResponseType.Type, completion : @escaping (ChooseLanguages.LanguagesModel.Response? , Error?) -> () ) {
        
        GoogleClient.taskForGetRequest(url: url, responseType: responseType) { (response, error) in
            
            if let error = error {
                completion(nil,error)
            }else{
                completion(response as? ChooseLanguages.LanguagesModel.Response ,nil)
            }
        }
        
    }
}
