//
//  ChooseLanguagesModels.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 22/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct ChooseLanguages
{
  // MARK: Use cases
  
    struct LanguagesModel : Codable{
        
        struct Request
        {
        }
        
        struct Response : Codable {
            let data : Languages
        }
        
        struct Languages : Codable {
            let languages : [Language]
        }
        
        struct ViewModel
        {
            let languages : [Language]
            let error : Error?
        }
        
    }
}
