//
//  ChooseLanguagesPresenter.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 22/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChooseLanguagesPresentationLogic
{
  //func presentSomething(response: ChooseLanguages.Something.Response)
    func presentLanguages(languages : [Language],error : Error?)
}

class ChooseLanguagesPresenter: ChooseLanguagesPresentationLogic
{
  weak var viewController: ChooseLanguagesDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: ChooseLanguages.Something.Response)
//  {
//    let viewModel = ChooseLanguages.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    func presentLanguages(languages : [Language],error : Error?) {
        if languages.isEmpty && error != nil {
            viewController?.displayLanguages(languages: [],error:error)
        }else{
            viewController?.displayLanguages(languages: languages, error: nil)
        }
    }
}
