//
//  TextTranslatorPresenter.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 21/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TextTranslatorPresentationLogic
{
  //func presentSomething(response: TextTranslator.Something.Response)
    func presentTranslatedText(translatedText : String,error : Error?)
}

class TextTranslatorPresenter: TextTranslatorPresentationLogic
{
  weak var viewController: TextTranslatorDisplayLogic?
  
  // MARK: Do something
  
    func presentTranslatedText(translatedText: String,error: Error?) {
        
        if let error = error as NSError?{
            
            viewController?.updateTranslatedText(translatedText: "Unable To Translate", error: error.localizedDescription)
        }else{
            viewController?.updateTranslatedText(translatedText: translatedText, error:nil )
        }
    }
    
//  func presentSomething(response: TextTranslator.Something.Response)
//  {
//    let viewModel = TextTranslator.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
