//
//  TextTranslatorWorker.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 21/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TextTranslatorWorker
{
  
    func getTranslation<ResponseType:Decodable> (url: URL,responseType : ResponseType.Type,completion : @escaping (TextTranslator.GoogleTranslation.TranslationResponse?,Error?) -> ()){
        GoogleClient.taskForGetRequest(url: url, responseType: responseType) { (response, error) in
            
            if let error = error {
                completion(nil,error)
            }else{
                completion(response as? TextTranslator.GoogleTranslation.TranslationResponse,nil)
            }
            
        }
    }
    
}
