//
//  TextTranslatorInteractor.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 21/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TextTranslatorBusinessLogic
{
  //func doSomething(request: TextTranslator.Something.Request)
    func getTranslation(sourceLang : String,targetLang :String,qText:String)
    
}

protocol TextTranslatorDataStore
{
  //var name: String { get set }
    var translation: String {get set}
}

class TextTranslatorInteractor: TextTranslatorBusinessLogic, TextTranslatorDataStore
{
    var translation: String = ""
    
  var presenter: TextTranslatorPresentationLogic?
  var worker: TextTranslatorWorker?
  //var name: String = ""
  
  // MARK: Get Translation
  
//  func doSomething(request: TextTranslator.Something.Request)
//  {
//    worker = TextTranslatorWorker()
//    worker?.doSomeWork()
//    
//    let response = TextTranslator.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
    func getTranslation(sourceLang: String, targetLang: String, qText: String) {
        worker = TextTranslatorWorker()
        worker?.getTranslation(url: GoogleClient.Endpoints.getTranslation(qText, targetLang, sourceLang).url, responseType: TextTranslator.GoogleTranslation.TranslationResponse.self, completion: { (response, error) in
            
            if let error = error {
                //Present error
                self.presenter?.presentTranslatedText(translatedText: "", error: error)
            }else{
                //Present Translated text
                self.presenter?.presentTranslatedText(translatedText: response!.data.translations[0].translatedText, error: nil)
            }
            
            
            
        })
    }
    
}
