//
//  TextTranslatorModels.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 21/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct TextTranslator
{
  // MARK: Use cases
  
  struct GoogleTranslation{
//    struct Request{
//        
//    }
    
    struct TranslationResponse: Codable{
        let data : Translations
    }
    
    struct Translations : Codable {
        let translations : [Translation]
    }

    struct Translation : Codable {
        let translatedText : String
    }
    
    struct TranslationTextViewModel{
        let translatedText : String
    }
    
  }
}
