//
//  TextTranslatorRouter.swift
//  TranslateAppArc
//
//  Created by PS Shortcut on 21/03/2019.
//  Copyright (c) 2019 Panagiotis Siapkaras. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TextTranslatorRoutingLogic
{
    func routeToSomewhere(segue: UIStoryboardSegue?,sender:Any?)
}

protocol TextTranslatorDataPassing
{
  var dataStore: TextTranslatorDataStore? { get }
}

class TextTranslatorRouter: NSObject, TextTranslatorRoutingLogic, TextTranslatorDataPassing
{
    
  weak var viewController: TextTranslatorViewController?
  var dataStore: TextTranslatorDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?, sender: Any?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ChooseLanguagesViewController
        let tag = sender as! Int
        destinationVC.buttonTag = tag
        destinationVC.delegate = viewController
        
        destinationVC.fromSelectedLanguage = viewController?.fromSelectedLanguage
        destinationVC.toSelectedLanguage = viewController?.toSelectedLanguage
    }
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
  }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TextTranslatorViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TextTranslatorDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
